### ISSUE TITLE
Seems I  download processed (blurred) files and not my unprocessed files ?

### ISSUE THREAD

**Issue by developery-nl** [gitouche-sur-osm/mapillary_takeout#4] opened 2020-06-23 22:03 UTC
Nice script. Thanks. Now busy downloading my 2016 uploads. But it seems I got downloads of processed (blurred) files and not my unprocessed files. Any explanation?

**Comment by gitouche-sur-osm** [comment] 2020-06-26 08:01
Hello,

I've had this feedback from other sources, but can't reproduce with my data for debugging.
For a specific blurred image, can you open it on the mapillary website, log in, and check with the "download unprocessed originals" for blurs?

![mpy-dl-unprocessed-originals](https://user-images.githubusercontent.com/64632866/85834116-1e9e7c80-b793-11ea-889d-f49bc733b841.png)

This is what the script automates, so it would help to know if mapillary is really sending the true unprocessed original.

**Comment by developery-nl** [comment] 2020-06-26 08:57
Hi. I checked that manual approach using the ""download unprocessed originals" and it also gives blurred images as result. So the issue is at mapillary and not in your tool. I remember when I tried it a year ago it gave me the 'real' unprocessed, but currently not.

Also, not sure if I do find it an issue personally; now I can re-use my downloads again with this privacy filter already applied. Being able to choose for processed / unprocessed would be better though..

**Comment by gitouche-sur-osm** [comment] 2020-06-26 10:21
> Hi. I checked that manual approach using the ""download unprocessed originals" and it also gives blurred images as result. So the issue is at mapillary and not in your tool. I remember when I tried it a year ago it gave me the 'real' unprocessed, but currently not.

That's what I thought. Thank you for the feedback. They might have lost some originals at some point...
Out of curiosity, can you tell me if these blurred images have exif data?

> Also, not sure if I do find it an issue personally; now I can re-use my downloads again with this privacy filter already applied. Being able to choose for processed / unprocessed would be better though..

Yes... mass download of the high resolution blurred images is only possible for organizations. The mapillary_tools "download" option covers this need.

Outside of organizations, we are limited to 2048px images : 
- with Mapillary watermark
- without any exif tags

Those are really useless if you can't place them on a map :-/
I don't plan to support download of these images in this script.

**Comment by developery-nl** [comment] 2020-06-26 11:09
> That's what I thought. Thank you for the feedback. They might have lost some originals at some point...
> Out of curiosity, can you tell me if these blurred images have exif data?

yes, Exif with gps present.

![image](https://user-images.githubusercontent.com/1163907/85851014-2fa8b700-b7ae-11ea-8c9b-9712532236ec.png)

**Comment by gitouche-sur-osm** [comment] 2020-06-26 12:10
Thank you. I checked my images and they are all fine, but I started in summer 2017.
Maybe they don't have the originals up to a certain point in time, between february and july 2017.
The 2048px resolution seems to indicate so, this is the "maximum" resolution used on the website itself.
At least you have the exif data so there is some value in taking them out :-)

**Comment by chk1** [comment] 2020-06-27 20:02
While browsing through the OSM forums I found this link and quote:

https://help.mapillary.com/hc/en-us/articles/115001662325-Mapillary-for-the-Web

>Download the original of any image that you have contributed (due to privacy regulations, **we keep the unblurred original for a limited time**; after that, only a blurred version will be retained but the size, resolution, and metadata will still be the same as the original)

My files until September 2019 are blurred too, the more recent ones I have from March/April 2020 are not blurred

**Comment by wosch** [comment] 2020-10-24 10:05
Won't fix.

**Closed as completed by wosch** 2020-10-24 10:05 UTC
Labels: documentation
